/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Employee.Login;
import java.awt.BorderLayout;
import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author MR-INT
 */
public class ConsultEmployee extends javax.swing.JFrame {
    
    MyConnection_Admin m = new MyConnection_Admin();
    private final Image img_find = new ImageIcon(Login.class.getResource("img/find.png")).getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH);

    /**
     * Creates new form ConsultEmployee
     */
    public ConsultEmployee() {
        initComponents();
        BtnFind.setIcon(new ImageIcon(img_find));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emp_form = new javax.swing.JPanel();
        lblfnemployee = new javax.swing.JLabel();
        lbllnemployee = new javax.swing.JLabel();
        lblstreetemployee = new javax.swing.JLabel();
        lblemployeecity = new javax.swing.JLabel();
        lblemployeephone = new javax.swing.JLabel();
        BtnRetour = new javax.swing.JButton();
        lblid1 = new javax.swing.JLabel();
        lblid2 = new javax.swing.JLabel();
        lblid3 = new javax.swing.JLabel();
        lblid4 = new javax.swing.JLabel();
        lblid5 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BtnFind = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        emp_form.setBackground(new java.awt.Color(38, 67, 72));
        emp_form.setPreferredSize(new java.awt.Dimension(866, 747));

        lblfnemployee.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblfnemployee.setForeground(new java.awt.Color(255, 255, 255));
        lblfnemployee.setText("First Name :");

        lbllnemployee.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbllnemployee.setForeground(new java.awt.Color(255, 255, 255));
        lbllnemployee.setText("Last Name :");

        lblstreetemployee.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblstreetemployee.setForeground(new java.awt.Color(255, 255, 255));
        lblstreetemployee.setText("Street :");

        lblemployeecity.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblemployeecity.setForeground(new java.awt.Color(255, 255, 255));
        lblemployeecity.setText("City :");

        lblemployeephone.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblemployeephone.setForeground(new java.awt.Color(255, 255, 255));
        lblemployeephone.setText("Phone :");

        BtnRetour.setBackground(javax.swing.UIManager.getDefaults().getColor("EditorPane.caretForeground"));
        BtnRetour.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BtnRetour.setForeground(new java.awt.Color(255, 255, 255));
        BtnRetour.setText("Back");
        BtnRetour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnRetourMouseClicked(evt);
            }
        });
        BtnRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRetourActionPerformed(evt);
            }
        });

        lblid1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblid1.setForeground(new java.awt.Color(153, 255, 255));
        lblid1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblid1.setText("Customer  Name");

        lblid2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblid2.setForeground(new java.awt.Color(153, 255, 255));
        lblid2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblid2.setText("Customer Last Name");

        lblid3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblid3.setForeground(new java.awt.Color(153, 255, 255));
        lblid3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblid3.setText("Street");

        lblid4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblid4.setForeground(new java.awt.Color(153, 255, 255));
        lblid4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblid4.setText("City");

        lblid5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblid5.setForeground(new java.awt.Color(153, 255, 255));
        lblid5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblid5.setText("Phone");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Account ID :");

        BtnFind.setBackground(new java.awt.Color(51, 51, 51));
        BtnFind.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BtnFind.setForeground(new java.awt.Color(255, 255, 255));
        BtnFind.setText("Find");
        BtnFind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnFindMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout emp_formLayout = new javax.swing.GroupLayout(emp_form);
        emp_form.setLayout(emp_formLayout);
        emp_formLayout.setHorizontalGroup(
            emp_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emp_formLayout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addGroup(emp_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(emp_formLayout.createSequentialGroup()
                        .addComponent(lblfnemployee, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblid1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 305, Short.MAX_VALUE)
                        .addComponent(BtnRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141))
                    .addGroup(emp_formLayout.createSequentialGroup()
                        .addGroup(emp_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(emp_formLayout.createSequentialGroup()
                                .addComponent(lbllnemployee, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblid2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(emp_formLayout.createSequentialGroup()
                                .addGroup(emp_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblstreetemployee, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblemployeecity, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblemployeephone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(emp_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblid3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblid4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblid5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(emp_formLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        emp_formLayout.setVerticalGroup(
            emp_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emp_formLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(emp_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(emp_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfnemployee)
                    .addComponent(lblid1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(emp_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllnemployee)
                    .addComponent(lblid2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(emp_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblstreetemployee)
                    .addComponent(lblid3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(emp_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblemployeecity)
                    .addComponent(lblid4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(emp_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblemployeephone)
                    .addComponent(lblid5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(306, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(emp_form, javax.swing.GroupLayout.DEFAULT_SIZE, 1199, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(emp_form, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRetourMouseClicked
           Employees emp = new Employees();
           if (emp_form.isShowing()) {

            emp_form.removeAll();
        }
        emp_form.removeAll();
        emp_form.repaint();
        emp_form.setLayout(new BorderLayout());
        emp_form.revalidate();

        emp_form.add(emp.employee_form, BorderLayout.CENTER);
    }//GEN-LAST:event_BtnRetourMouseClicked

    private void BtnRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRetourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRetourActionPerformed

    private void BtnFindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnFindMouseClicked
      
            m.Findcust(txtid,lblid1,lblid2,lblid3,lblid4,lblid5);
        
    }//GEN-LAST:event_BtnFindMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnFind;
    public javax.swing.JButton BtnRetour;
    public javax.swing.JPanel emp_form;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lblemployeecity;
    public javax.swing.JLabel lblemployeephone;
    public javax.swing.JLabel lblfnemployee;
    public javax.swing.JLabel lblid1;
    public javax.swing.JLabel lblid2;
    public javax.swing.JLabel lblid3;
    public javax.swing.JLabel lblid4;
    public javax.swing.JLabel lblid5;
    public javax.swing.JLabel lbllnemployee;
    public javax.swing.JLabel lblstreetemployee;
    public javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
